backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Banner Image", name: "bannerImage", widget: "object", required: true, fields: [{label: "Image", name: "image", widget: "image", required: true}, {label: "Alt", name: "alt", widget: "string"}]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description (150 characters max.)", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "employee"
    identifier_field: "name"
    extension: "yml"
    label: "Employees"
    label_singular: "Employee"
    folder: "src/employees"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Credentials", name: "credentials", widget: "string", required: false}
      - {label: "Profile Image", name: "profileImage", widget: "object", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"}]}
      - {label: "Publish Date (Team members will be displayed according to date, in ascending order)", name: "date", widget: "datetime"}
      - {label: "Bio", name: "bio", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKay", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "markdown"}
          - {label: "Heading", name: "heading"}
          - {label: "Text", name: "text", widget: "markdown"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "markdown"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/services/index.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/tools-resources/index.md"
        label: "Tools & Resources"
        name: "tools-resources"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/faq/index.md"
        label: "FAQ"
        name: "faq"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "faq-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Questions", name: "questions", widget: "list", fields: [{label: "Question", name: "question", widget: "string"}, {label: "Answer", name: "answer", widget: "markdown"}]}